# Generated by Django 4.0.3 on 2022-04-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cym', models.CharField(max_length=16, unique=True)),
                ('cphm', models.CharField(max_length=16)),
                ('xszzb', models.ImageField(upload_to='car/pictures')),
                ('xszfb', models.ImageField(upload_to='car/pictures')),
                ('cldjsj', models.CharField(max_length=32)),
                ('clgls', models.CharField(max_length=32)),
                ('clzk', models.CharField(max_length=32)),
                ('pcqk', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'car_table',
            },
        ),
        migrations.CreateModel(
            name='Car_anpai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cym', models.CharField(max_length=16)),
                ('jsy', models.CharField(max_length=16)),
                ('ycsy', models.CharField(max_length=128)),
                ('pcsj', models.DateTimeField(auto_now_add=True)),
                ('ghsj', models.DateTimeField(auto_now=True)),
                ('csyf', models.CharField(max_length=16)),
                ('csgls', models.CharField(max_length=16)),
                ('syclzk', models.CharField(max_length=32)),
                ('pcqk', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'car_anpai_table',
            },
        ),
    ]
