# Generated by Django 4.0.3 on 2022-04-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xm', models.CharField(max_length=8)),
                ('sfzh', models.CharField(max_length=32)),
                ('sjhm', models.CharField(max_length=16)),
                ('xb', models.CharField(max_length=2)),
                ('nl', models.CharField(max_length=2)),
                ('zw', models.CharField(max_length=8)),
                ('gj', models.CharField(max_length=8)),
                ('nsr', models.CharField(max_length=16)),
                ('xl', models.CharField(max_length=8)),
                ('hyzk', models.CharField(max_length=4)),
                ('zzmm', models.CharField(max_length=8)),
                ('hjxx', models.CharField(max_length=255)),
                ('tc', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'people_table',
            },
        ),
    ]
